In [35]:
import numpy as np

1. Input data

2. Linear combination (W*x + b)

3. Activation function (sigmoid)

4. Loss funtion (MSE)

5. Optimization (gradient descent)

6. Prediction

# 1. Input data

In [36]:
x = np.array([[0,0], [0,1], [1,0], [1,1]])
x

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

# 2. Linear combination (W*x + b)

In [37]:
def linear_c(x):
    W = np.random.randn(2)
    b = np.random.randn(1)

    return np.dot(W, x) + b

# 3. Activation function (sigmoid)

In [38]:
def sigmoid(a):
    return 1 / (1 + np.exp(a))

# 4. Loss funtion (MSE)

In [39]:
def MSE(pred_x, true_x):
    return 0.5 * np.sum((pred_x - true_x)**2)

# 5. Optimization (gradient descent)

In [40]:
# new_w = old_w - learning_rate * df_dx

def grad(f, x, learning_rate = 1e-5):
    
    def df_dx(f, x):
        h = 1e-7
        f_x = f(x)
        f_x_h = f(x+h)

        return (f_x_h - f_x) / h
    
    new_x = x - learning_rate * df_dx(f, x)
    
    return new_x


# 6. Prediction

Logit_gate라는 Class를 만들어서 1~5 과정을 전부 다 집어넣고 fit 메서드를 추가로 만들어서 학습을 가능하게 만듦.

Class Logit_gate():  
    1. weight_init()  
    2. linear_combi()  
    3. activation_function() * sigmoid  
    4. loss_function() * MSE  
    5. optimaiztion() * gradient descent  
    6. fit  
    7. prediction  

In [41]:
import numpy as np

def sigmoid(a):
    return 1 / (1 + np.exp(-a))



class Logit_gate():
    def __init__(self, learning_rate = 1e-1, activation = 'sigmoid', loss = 'MSE', opt = 'gradient', epochs = 1000) -> None:
        def weight_init():
            W = np.random.randn(2, 1)
            b = np.random.randn(1)

            return W, b
        
        self.W, self.b = weight_init()
        self.lr = learning_rate
        self.act_f = activation
        self.loss_f = loss
        self.opt = opt
        self.epochs = epochs

    def forpass(self, x):
        return self.activation_funtion(self.linear_combination(x))


    def backprop(self, x, err):
        m = len(x)
        w_grad = np.dot(x.T, err) / m
        b_grad = np.sum(err) / m
        return w_grad, b_grad


    def linear_combination(self, X):
        a = np.dot(X, self.W) + self.b
        return a


    def activation_funtion(self, a): # sigmoid
        if self.act_f == 'sigmoid':
            return sigmoid(a)


    def loss_funtion(self, x, y): # MSE
        if self.loss_f == 'MSE':
            return 0.5 * np.mean(np.sum((y - self.forpass(x))**2))


    def optimization(self, x, y): # gradient descent
        if self.opt == 'gradient':
            for i in range(self.epochs):
                err = -(y - self.forpass(x))
                w_gard, b_gard = self.backprop(x, err)
                self.W -= w_gard * self.lr
                self.b -= b_gard * self.lr


    def fit(self, X, y):
        self.optimization(X, y)
    

    def prediction(self, X):
        return self.activation_funtion(np.dot(X, self.W) + self.b)
           

In [42]:
OR = Logit_gate()

x_or = np.array([[0,0], [0,1], [1,0], [1,1]])
y_or = np.array([[0], [1], [1], [1]])

OR.fit(x_or, y_or)

OR.prediction(x_or)

array([[0.17782113],
       [0.92774729],
       [0.93395067],
       [0.99881021]])

In [43]:
AND = Logit_gate()

x_and = np.array([[0,0], [0,1], [1,0], [1,1]])
y_and = np.array([[0], [0], [0], [1]])

AND.fit(x_and, y_and)

AND.prediction(x_and)

array([[0.00650694],
       [0.13887537],
       [0.14058824],
       [0.80111572]])

In [44]:
NOR = Logit_gate()

x_nor = np.array([[0,0], [0,1], [1,0], [1,1]])
y_nor = np.array([[1], [0], [0], [0]])

NOR.fit(x_nor, y_nor)

NOR.prediction(x_nor)

array([[0.82508587],
       [0.06814085],
       [0.06808716],
       [0.00113131]])

In [45]:
NAND = Logit_gate()

x_nand = np.array([[0,0], [0,1], [1,0], [1,1]])
y_nand = np.array([[1], [1], [1], [0]])

NAND.fit(x_nand, y_nand)

NAND.prediction(x_nand)

array([[0.99072702],
       [0.84606005],
       [0.84591147],
       [0.22021407]])

In [80]:
# XOR gate

x = np.array([[0,0], [0,1], [1,0], [1,1]])

x_by_nand = NAND.prediction(x)
x_by_or = OR.prediction(x)

# x_xor = np.concatenate((x_by_nand, x_by_or), axis=1).reshape(4,2)
x_xor = np.array([x_by_nand, x_by_or]).T.reshape(-1, 2)

AND.prediction(x_xor)

array([[0.21916002],
       [0.66070474],
       [0.66503909],
       [0.24604145]])