1. Input data

2. Linear combination (W*x + b)

3. Activation function (sigmoid)

4. Loss funtion (MSE)

5. Optimization (gradient descent)

6. Prediction

# Class Logit_gate

Class Logit_gate():  

1. weight_init  
2. linear_combilinear_combination  
  a. forpass  
  b. backprop  
3. activation_function * sigmoid    
  a. sigmoid  
4. loss_function * MSE    
5. optimaiztion * gradient descent    
6. fit    
7. prediction    

In [1]:
import numpy as np

def sigmoid(a):
    return 1 / (1 + np.exp(-a))



class Logit_gate():
    def __init__(self, learning_rate = 1e-1, activation = 'sigmoid', loss = 'MSE', opt = 'gradient', epochs = 1000) -> None:
        def weight_init():
            W = np.random.randn(2, 1)
            b = np.random.randn(1)

            return W, b
        
        self.W, self.b = weight_init()
        self.lr = learning_rate
        self.act_f = activation
        self.loss_f = loss
        self.opt = opt
        self.epochs = epochs


    def forpass(self, x):
        return self.activation_funtion(self.linear_combination(x))


    def backprop(self, x, err):
        m = len(x)
        w_grad = np.dot(x.T, err) / m
        b_grad = np.sum(err) / m
        return w_grad, b_grad


    def linear_combination(self, X):
        a = np.dot(X, self.W) + self.b
        return a


    def activation_funtion(self, a): # sigmoid
        if self.act_f == 'sigmoid':
            return sigmoid(a)


    def loss_funtion(self, x, y): # MSE
        if self.loss_f == 'MSE':
            return 0.5 * np.mean(np.sum((y - self.forpass(x))**2))


    def optimization(self, x, y): # gradient descent
        if self.opt == 'gradient':
            for i in range(self.epochs):
                err = -(y - self.forpass(x))
                w_gard, b_gard = self.backprop(x, err)
                self.W -= w_gard * self.lr
                self.b -= b_gard * self.lr


    def fit(self, X, y):
        self.optimization(X, y)
    

    def prediction(self, X):
        return self.activation_funtion(np.dot(X, self.W) + self.b)
           

In [2]:
OR = Logit_gate()

x_or = np.array([[0,0], [0,1], [1,0], [1,1]])
y_or = np.array([[0], [1], [1], [1]])

OR.fit(x_or, y_or)

OR.prediction(x_or)

array([[0.18357803],
       [0.92556201],
       [0.9318844 ],
       [0.9986799 ]])

In [3]:
AND = Logit_gate()

x_and = np.array([[0,0], [0,1], [1,0], [1,1]])
y_and = np.array([[0], [0], [0], [1]])

AND.fit(x_and, y_and)

AND.prediction(x_and)

array([[0.00802803],
       [0.14942949],
       [0.14671914],
       [0.78869959]])

In [4]:
NOR = Logit_gate()

x_nor = np.array([[0,0], [0,1], [1,0], [1,1]])
y_nor = np.array([[1], [0], [0], [0]])

NOR.fit(x_nor, y_nor)

NOR.prediction(x_nor)

array([[0.79145218],
       [0.0814031 ],
       [0.07938096],
       [0.00200937]])

In [5]:
NAND = Logit_gate()

x_nand = np.array([[0,0], [0,1], [1,0], [1,1]])
y_nand = np.array([[1], [1], [1], [0]])

NAND.fit(x_nand, y_nand)

NAND.prediction(x_nand)

array([[0.99263202],
       [0.85590849],
       [0.85485142],
       [0.20614331]])

In [9]:
# XOR gate

x = np.array([[0,0], [0,1], [1,0], [1,1]])

x_by_nand = NAND.prediction(x)
x_by_or = OR.prediction(x)

# x_xor = np.concatenate((x_by_nand, x_by_or), axis=1).reshape(4,2)
x_xor = np.array([x_by_nand, x_by_or]).T.reshape(-1, 2)

AND.prediction(x_xor)

array([[0.22827215],
       [0.65647804],
       [0.66012826],
       [0.24728727]])